version: 2
jobs:
  build:
    working_directory: /workspace
    docker:
      - image: registry.gitlab.com/rayriffy/rayriffy-com/composer-yarn:latest
        auth:
          username: $REGISTRY_USER
          password: $REGISTRY_PASS
        environment:
          DEPLOY_HOST: $DEPLOY_HOST
          DEPLOY_COMMAND: $DEPLOY_COMMAND
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        environment:
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
          MYSQL_DATABASE: homestead
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - checkout
      - run:
          name: Install required packages & Configuration
          command: |
            apk update && apk add alpine-sdk
      - run:
          name: Config .env file
          command: |
            cp .env.example .env
      - run:
          name: Manage Composer Packages
          command: |
            composer install
      - run:
          name: Generate Key
          command: |
            php artisan key:generate
      - run:
          name: Migrate Database
          command: |
            php artisan migrate --force
  deploy:
    machine:
        enabled: true
    working_directory: /workspace
    steps:
      - run:
          name: Get rayriffy-com repo
          command: |
            git pull git@gitlab.com:rayriffy/rayriffy-com.git
            cd rayriffy-com/web/data/html/rfe.ivaothai.com
            rm -rf *
      - checkout
      - run:
          name: Remove git folder
          command: |
          ls -l -a
          rm -rf .git/
      - run:
          name: Push
          command: |
            git push origin master
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: release